package stepdefinitions.login;

import io.cucumber.java.Before;
import io.cucumber.java.After;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.When;
import io.cucumber.java.en.Then;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import pages.LoginPage;
import com.github.javafaker.Faker;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Step definitions for Login scenarios
 * Handles: happy path, invalid password, invalid username
 */
public class LoginStepDefinitions {

    private WebDriver driver;
    private LoginPage loginPage;
    private String generatedPassword;
    private String generatedUsername;
    private Faker faker;

    /**
     * Setup - Executed BEFORE each scenario
     * Creates fresh WebDriver instance for each scenario
     */
    @Before
    public void setUp() {
        System.out.println("\n========== SCENARIO STARTED ==========");
        System.out.println("Cucumber @Before: Setting up fresh WebDriver...");

        // Configure Chrome options
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--start-maximized");
        options.addArguments("--incognito");
        options.addArguments("--disable-notifications");
        options.addArguments("--disable-popup-blocking");
        options.addArguments("--disable-blink-features=AutomationControlled");
        options.setExperimentalOption("excludeSwitches", new String[]{"enable-automation"});
        options.setExperimentalOption("useAutomationExtension", false);

        // Initialize WebDriver (fresh instance for each scenario)
        driver = new ChromeDriver(options);
        loginPage = new LoginPage(driver);
        faker = new Faker();

        System.out.println("✓ WebDriver initialized (fresh instance)");
        System.out.println("✓ LoginPage object created");
    }

    /**
     * Teardown - Executed AFTER each scenario
     * Closes WebDriver properly
     */
    @After
    public void tearDown() {
        if (driver != null) {
            driver.quit();
            System.out.println("✓ WebDriver closed");
        }
        System.out.println("========== SCENARIO COMPLETED ==========\n");
    }

    // GIVEN Steps

    /**
     * Given: User is on the login page
     */
    @Given("the user is on the login page")
    public void userIsOnLoginPage() {
        System.out.println("\n[GIVEN] User navigating to login page...");
        loginPage.navigateToLoginPage();
        System.out.println("✓ User is now on login page");
    }

    // WHEN Steps

    /**
     * When: User enters username
     */
    @When("the user enters username {string}")
    public void userEntersUsername(String username) {
        System.out.println("\n[WHEN] User entering username: " + username);
        loginPage.enterUsername(username);
    }

    /**
     * When: User enters password
     */
    @When("the user enters password {string}")
    public void userEntersPassword(String password) {
        System.out.println("\n[WHEN] User entering password: (hidden for security)");
        loginPage.enterPassword(password);
    }

    /**
     * When: User enters invalid password generated by Faker
     */
    @When("the user enters an invalid password generated by Faker")
    public void userEntersInvalidPasswordFromFaker() {
        System.out.println("\n[WHEN] Generating invalid password with Faker...");

        generatedPassword = faker.internet().password();

        System.out.println("✓ Invalid password generated (hidden for security)");
        System.out.println("ℹ️  Note: Password is different from 'secret_sauce'");

        loginPage.enterPassword(generatedPassword);
    }

    /**
     * When: User enters invalid username generated by Faker
     */
    @When("the user enters an invalid username generated by Faker")
    public void userEntersInvalidUsernameFromFaker() {
        System.out.println("\n[WHEN] Generating invalid username with Faker...");

        generatedUsername = faker.name().username();

        System.out.println("✓ Invalid username generated: " + generatedUsername);
        System.out.println("ℹ️  Note: This username does not exist in the system");

        loginPage.enterUsername(generatedUsername);
    }

    /**
     * When: User clicks the login button
     */
    @When("the user clicks the login button")
    public void userClicksLoginButton() {
        System.out.println("\n[WHEN] User clicking login button...");
        loginPage.clickLoginButton();

        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
        System.out.println("✓ Login button clicked");
    }

    // THEN Steps

    /**
     * Then: User should be redirected to inventory page
     */
    @Then("the user should be redirected to the inventory page")
    public void userIsRedirectedToInventoryPage() {
        System.out.println("\n[THEN] Validating redirection to inventory page...");

        String currentUrl = driver.getCurrentUrl();
        assertTrue(
            currentUrl.contains("inventory"),
            "ERROR: Should be redirected to inventory page. Current URL: " + currentUrl
        );
        System.out.println("✓ ASSERTION PASSED: User is on inventory page");
    }

    /**
     * Then: Error message should be displayed
     */
    @Then("an error message should be displayed")
    public void errorMessageShouldBeDisplayed() {
        System.out.println("\n[THEN] Validating error message is displayed...");

        assertTrue(
            loginPage.isErrorMessageDisplayed(),
            "ERROR: Error message should be displayed!"
        );
        System.out.println("✓ ASSERTION PASSED: Error message is displayed");
    }

    /**
     * Then: Error message should contain specific text
     */
    @Then("the error message should contain {string}")
    public void errorMessageShouldContain(String expectedText) {
        System.out.println("\n[THEN] Validating error message contains: " + expectedText);

        String actualMessage = loginPage.getErrorMessage();
        assertTrue(
            actualMessage.contains(expectedText),
            "ERROR: Message should contain '" + expectedText + "'. Actual: " + actualMessage
        );
        System.out.println("✓ ASSERTION PASSED: Error message contains '" + expectedText + "'");
    }

    /**
     * Then: Error icons should be visible
     */
    @Then("error icons should be visible")
    public void errorIconsShouldBeVisible() {
        System.out.println("\n[THEN] Validating error icons are visible...");

        assertTrue(
            loginPage.areErrorIconsDisplayed(),
            "ERROR: Error icons should be visible!"
        );
        System.out.println("✓ ASSERTION PASSED: Error icons are visible");
    }

    /**
     * Then: Both username and password fields should have error styling
     */
    @Then("both username and password fields should have error styling")
    public void bothFieldsShouldHaveErrorStyling() {
        System.out.println("\n[THEN] Validating error styling on both fields...");

        boolean usernameHasError = loginPage.doesUsernameFieldHaveErrorClass();
        boolean passwordHasError = loginPage.doesPasswordFieldHaveErrorClass();

        assertTrue(
            usernameHasError,
            "ERROR: Username field should have error styling"
        );

        assertTrue(
            passwordHasError,
            "ERROR: Password field should have error styling"
        );
        System.out.println("✓ ASSERTION PASSED: Both fields have error styling");
    }

    /**
     * Then: User should remain on login page
     */
    @Then("the user should remain on the login page")
    public void userShouldRemainOnLoginPage() {
        System.out.println("\n[THEN] Validating user is still on login page...");

        String currentUrl = driver.getCurrentUrl();
        assertTrue(
            currentUrl.contains("saucedemo.com") && !currentUrl.contains("inventory"),
            "ERROR: User should remain on login page. Current URL: " + currentUrl
        );
        System.out.println("✓ ASSERTION PASSED: User remains on login page");
    }
}
