Feature: Login - Authentication Scenarios
  As a user
  I want to login to the application
  So that I can validate authentication with valid and invalid credentials

  @login @happy-path @smoke
  Scenario: Should successfully login with valid credentials
    Given the user is on the login page
    When the user enters username "standard_user"
    And the user enters password "secret_sauce"
    And the user clicks the login button
    Then the user should be redirected to the inventory page

  @login @negative @invalid-password
  Scenario: Should fail login with invalid password
    Given the user is on the login page
    When the user enters username "standard_user"
    And the user enters an invalid password generated by Faker
    And the user clicks the login button
    Then an error message should be displayed
    And the error message should contain "Epic sadface"
    And error icons should be visible
    And both username and password fields should have error styling

  @login @negative @invalid-username
  Scenario: Should fail login with invalid username
    Given the user is on the login page
    When the user enters an invalid username generated by Faker
    And the user enters password "secret_sauce"
    And the user clicks the login button
    Then an error message should be displayed
    And the error message should contain "Username and password do not match"
    And both username and password fields should have error styling
    And error icons should be visible
    And the user should remain on the login page

